name: blueprint
director_uuid: <%= `bosh status --uuid` %>

releases:
- name: blueprint
  version: latest

stemcells:
- alias: ubuntu-trusty
  name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
  version: latest

update:
  canaries: 1
  canary_watch_time: 30000-240000
  update_watch_time: 30000-600000
  max_in_flight: 3

instance_groups:
- name: blueprint
  migrated_from:
  - name: blueprint_z1
    az: z1
  instances: 1
  networks:
  - name: sf_bosh_services
    static_ips:
    - 10.11.45.112
  vm_type: service_fabrik_vm_micro
  persistent_disk_type: service_fabrik_hdd_1gb
  azs:
  - z1
  stemcell: ubuntu-trusty
  jobs:
  - name: blueprint
    release: blueprint
    blueprint:
    properties:
      port: 8080
      admin:
        username: admin
        password: admin
  - name: broker-agent
    release: blueprint
    properties:
      username: service-fabrik-blueprint-agent
      password: service-fabrik-blueprint-secret
      provider:
